# 项目相关配置
bluewind:
  # 名称
  name: bluewind-shorturl
  # 版本
  version: 1.0.0
  # 数据库类型
  db-type: mysql
  # 短链域名/外网ip
  inet-address: http://127.0.0.1:${server.port}/

server:
  port: 8076
  servlet:
    session:
      timeout: 1800s
    # 设置编码
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shortlink?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fanny136

  #静态资源配置
  resources:
    static-locations: classpath:/static/
  #thymeleaf模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  #Redis配置
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
#    password: 123654 # Redis服务器连接密码（默认为空）
    database: 0 #Redis数据库索引（默认为0）
    timeout: 10s # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 12 # 连接池最大连接数（使用负值表示没有限制），生产环境一般设置为大于cpu*2
        max-idle: 8 # 连接池中的最大空闲连接数，生产环境一般设置为cpu*2
        min-idle: 0 # 连接池中的最小空闲连接数
        max-wait: 5s # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # 邮箱配置信息
  mail:
    host: smtp.qq.com
    port: 587
    username: 1527451967@qq.com
    password: ifoabddipygyhbbe
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true

logging:
  level:
    com.bluewind.shorturl: info
    org.springframework: warn

# springboot异步线程配置
async:
  executor:
    thread:
      core_pool_size: 5 #配置核心线程数
      keep_alive_seconds: 60 #设置线程活跃时间（秒）
      max_pool_size: 10 #配置最大线程数
      name_prefix: async-service- #配置线程池中的线程的名称前缀
      queue_capacity: 100 #配置队列大小

# 用户密码加密的盐
hash:
  salt: ymp8R3Vg7Kv5$y5fM3*xl&ins7SZcTEY